# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.cache/wt} [current_project]
set_property parent.project_path {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/imports/sources_1/new/Adder8bit.vhd}
  {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/imports/sources_1/imports/new/And8bit.vhd}
  {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/imports/sources_1/imports/new/AndSinleBit.vhd}
  {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/imports/new/BinarytoSevenSegment.vhd}
  {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/imports/sources_1/imports/new/FullAdder.vhd}
  {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/imports/sources_1/imports/new/FullSubtract.vhd}
  {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/imports/sources_1/imports/new/Nand8bit.vhd}
  {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/imports/sources_1/imports/new/Or8bit.vhd}
  {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/imports/sources_1/imports/new/OrSinleBit.vhd}
  {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/imports/sources_1/new/PsuedoRandom.vhd}
  {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/imports/sources_1/imports/new/SinglebitNand.vhd}
  {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/imports/sources_1/imports/new/Subtract8bit.vhd}
  {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/imports/sources_1/imports/new/Xor8bit.vhd}
  {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/imports/sources_1/imports/new/XorSinleBit.vhd}
  {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/imports/sources_1/imports/new/adder16bit.vhd}
  {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/imports/sources_1/new/multiplier8bit.vhd}
  {C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/new/toplevel.vhd}
}
read_ip -quiet {{C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/constrs_1/imports/Basys3/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/prith/Desktop/ECE/CHD/Livado HWs/UART/UART.srcs/constrs_1/imports/Basys3/Basys3_Master.xdc}}]


synth_design -top toplevel -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef toplevel.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file toplevel_utilization_synth.rpt -pb toplevel_utilization_synth.pb"
