# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/CHD_HW/hw_3/hw_3.cache/wt [current_project]
set_property parent.project_path G:/CHD_HW/hw_3/hw_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo g:/CHD_HW/hw_3/hw_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  G:/CHD_HW/hw_3/hw_3.srcs/sources_1/imports/sources_1/imports/new/BinaryToSevenSegment.vhd
  G:/CHD_HW/hw_3/hw_3.srcs/sources_1/imports/new/FullAdder.vhd
  G:/CHD_HW/hw_3/hw_3.srcs/sources_1/new/FullSubtractor.vhd
  G:/CHD_HW/hw_3/hw_3.srcs/sources_1/new/Subtract.vhd
  G:/CHD_HW/hw_3/hw_3.srcs/sources_1/new/adder16bit.vhd
  G:/CHD_HW/hw_3/hw_3.srcs/sources_1/imports/new/adder8bit.vhd
  G:/CHD_HW/hw_3/hw_3.srcs/sources_1/imports/new/multiplier8bit.vhd
  G:/CHD_HW/hw_3/hw_3.srcs/sources_1/imports/sources_1/new/register8bit.vhd
  G:/CHD_HW/hw_3/hw_3.srcs/sources_1/imports/toplevel.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/CHD_HW/hw_3/hw_3.srcs/constrs_1/imports/Basys3/Basys3_Master.xdc
set_property used_in_implementation false [get_files G:/CHD_HW/hw_3/hw_3.srcs/constrs_1/imports/Basys3/Basys3_Master.xdc]


synth_design -top toplevel -part xc7a35tcpg236-1


write_checkpoint -force -noxdef toplevel.dcp

catch { report_utilization -file toplevel_utilization_synth.rpt -pb toplevel_utilization_synth.pb }
